// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.Database;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203223138_AddSessionCompletionFields")]
    partial class AddSessionCompletionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.Database.AvailableDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TutorScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorScheduleId");

                    b.ToTable("AvailableDays");
                });

            modelBuilder.Entity("Services.Database.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TutorId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Services.Database.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Services.Database.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bosnian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "French"
                        },
                        new
                        {
                            Id = 4,
                            Name = "German"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Japanese"
                        });
                });

            modelBuilder.Entity("Services.Database.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Embarking on the language journey, learning greetings and essential words.",
                            MaxPoints = 100,
                            Name = "Wanderer",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Navigating simple conversations and discovering basic grammar structures.",
                            MaxPoints = 200,
                            Name = "Explorer",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Confidently sharing stories and engaging in daily discussions.",
                            MaxPoints = 400,
                            Name = "Storyteller",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mastering complex topics, idioms, and nuanced expressions.",
                            MaxPoints = 600,
                            Name = "Sage",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Achieving legendary fluency and cultural mastery, speaking like a native.",
                            MaxPoints = 1000,
                            Name = "Polyglot",
                            Order = 5
                        });
                });

            modelBuilder.Entity("Services.Database.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "UserId", "CommentId" }, "IX_Like_User_Comment")
                        .IsUnique()
                        .HasFilter("[CommentId] IS NOT NULL");

                    b.HasIndex(new[] { "UserId", "PostId" }, "IX_Like_User_Post")
                        .IsUnique()
                        .HasFilter("[PostId] IS NOT NULL");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Services.Database.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Content = "Bonjour! Today I want to share my experience learning French. It's been an amazing journey!",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "My French Learning Journey"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Content = "Learning a new language opens doors to new cultures and perspectives. I've been studying German for 6 months now and I'm loving every moment of it. The grammar can be challenging, but practice makes perfect!",
                            CreatedAt = new DateTime(2025, 11, 25, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Why I Love Learning German"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            Content = "日本語を勉強しています。とても楽しいです！",
                            CreatedAt = new DateTime(2025, 11, 26, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "日本語の勉強"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 5,
                            Content = "English is such a versatile language. Whether you're traveling, working, or just connecting with people from around the world, English skills are invaluable.",
                            CreatedAt = new DateTime(2025, 11, 2, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "The Power of English"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            Content = "Bosanski jezik je predivan! Učim ga već godinu dana i svaki dan otkrivam nešto novo.",
                            CreatedAt = new DateTime(2025, 11, 23, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Učenje bosanskog jezika"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 7,
                            Content = "French pronunciation can be tricky, but here are some tips that helped me: focus on nasal sounds, practice with native speakers, and don't be afraid to make mistakes!",
                            CreatedAt = new DateTime(2025, 11, 18, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "French Pronunciation Tips"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Content = "German compound words are fascinating. Did you know that 'Donaudampfschiffahrtsgesellschaftskapitän' is a real word?",
                            CreatedAt = new DateTime(2025, 10, 21, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Fascinating German Words"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 9,
                            Content = "今日は天気がいいですね。",
                            CreatedAt = new DateTime(2025, 11, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "今日の天気"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 10,
                            Content = "Language learning is not just about memorizing vocabulary. It's about understanding culture, history, and the way people think. When I started learning Japanese, I discovered a whole new way of expressing ideas.",
                            CreatedAt = new DateTime(2025, 11, 23, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Beyond Vocabulary: Understanding Culture"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 11,
                            Content = "Practice speaking every day, even if it's just for 10 minutes. Consistency is key!",
                            CreatedAt = new DateTime(2025, 10, 19, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Daily Practice Matters"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Content = "I love how different languages express the same concept differently. In English we say 'I'm hungry', but in French it's 'J'ai faim' which literally means 'I have hunger'. So interesting!",
                            CreatedAt = new DateTime(2025, 11, 19, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Interesting Language Differences"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Content = "Bosnian grammar has cases, which can be challenging for English speakers. But once you understand the pattern, it becomes much easier.",
                            CreatedAt = new DateTime(2025, 11, 18, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Mastering Bosnian Cases"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            Content = "Watching movies in the target language with subtitles is a great way to improve listening skills. I've been doing this with French films and it's really helping!",
                            CreatedAt = new DateTime(2025, 11, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Learning Through Movies"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            Content = "Language exchange is amazing. I found a language partner online and we practice speaking twice a week. It's free and very effective!",
                            CreatedAt = new DateTime(2025, 11, 14, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Language Exchange Benefits"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 6,
                            Content = "今日、新しい漢字を学びました。",
                            CreatedAt = new DateTime(2025, 11, 11, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "新しい漢字"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            Content = "Don't worry about making mistakes. Every native speaker makes mistakes too. The important thing is to communicate and keep learning. I've been learning German for a year now, and I still make plenty of errors, but I can have conversations and that's what matters!",
                            CreatedAt = new DateTime(2025, 11, 18, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Don't Fear Mistakes"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 8,
                            Content = "Reading books in your target language is challenging at first, but it's one of the best ways to expand vocabulary. Start with children's books and work your way up.",
                            CreatedAt = new DateTime(2025, 11, 2, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Reading in Target Language"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            Content = "French culture is so rich and diverse. Learning the language has given me insights into French history, art, literature, and cuisine. It's like opening a window to a whole new world!",
                            CreatedAt = new DateTime(2025, 12, 1, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "French Culture Insights"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            Content = "Consistency beats intensity. It's better to study for 20 minutes every day than to cram for 3 hours once a week. I've been following this approach with Japanese and I'm seeing great progress!",
                            CreatedAt = new DateTime(2025, 10, 16, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Consistency is Key"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            Content = "Language learning apps are helpful, but nothing beats real conversation. Find opportunities to speak with native speakers, whether online or in person. It's the fastest way to improve!",
                            CreatedAt = new DateTime(2025, 10, 30, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            ImageUrl = "",
                            Title = "Real Conversation Practice"
                        });
                });

            modelBuilder.Entity("Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Services.Database.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentNumOfUSers")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("NumOfUsers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Services.Database.StudentLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2025, 11, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 1,
                            LevelId = 2,
                            Points = 75,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2025, 11, 18, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 3,
                            LevelId = 1,
                            Points = 45,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2025, 10, 4, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 4,
                            LevelId = 3,
                            Points = 320,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2025, 11, 13, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 5,
                            LevelId = 1,
                            Points = 85,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2025, 9, 4, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 2,
                            LevelId = 4,
                            Points = 550,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2025, 10, 19, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 1,
                            LevelId = 2,
                            Points = 120,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2025, 11, 8, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 3,
                            LevelId = 1,
                            Points = 60,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2025, 10, 14, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 4,
                            LevelId = 2,
                            Points = 180,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2025, 9, 19, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 5,
                            LevelId = 3,
                            Points = 380,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2025, 11, 23, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            LanguageId = 2,
                            LevelId = 1,
                            Points = 95,
                            StudentId = 11
                        });
                });

            modelBuilder.Entity("Services.Database.StudentTutorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<string>("channelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("StudentTutorSessions");
                });

            modelBuilder.Entity("Services.Database.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4CAF50",
                            Name = "Conversation"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#2196F3",
                            Name = "Grammar"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FF9800",
                            Name = "Pronunciation"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#9C27B0",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FF5722",
                            Name = "Food & Cooking"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#607D8B",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#E91E63",
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#795548",
                            Name = "Daily Life"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#00BCD4",
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#8BC34A",
                            Name = "Health & Wellness"
                        });
                });

            modelBuilder.Entity("Services.Database.TutorLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("PricePerHour")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Experience = 10,
                            LanguageId = 1,
                            LevelId = 5,
                            PricePerHour = 35,
                            TutorId = 2
                        },
                        new
                        {
                            Id = 2,
                            Experience = 8,
                            LanguageId = 3,
                            LevelId = 4,
                            PricePerHour = 30,
                            TutorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Experience = 15,
                            LanguageId = 5,
                            LevelId = 5,
                            PricePerHour = 40,
                            TutorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Experience = 12,
                            LanguageId = 1,
                            LevelId = 4,
                            PricePerHour = 35,
                            TutorId = 3
                        },
                        new
                        {
                            Id = 5,
                            Experience = 9,
                            LanguageId = 4,
                            LevelId = 5,
                            PricePerHour = 32,
                            TutorId = 4
                        },
                        new
                        {
                            Id = 6,
                            Experience = 11,
                            LanguageId = 2,
                            LevelId = 5,
                            PricePerHour = 28,
                            TutorId = 4
                        },
                        new
                        {
                            Id = 7,
                            Experience = 7,
                            LanguageId = 3,
                            LevelId = 5,
                            PricePerHour = 30,
                            TutorId = 5
                        },
                        new
                        {
                            Id = 8,
                            Experience = 6,
                            LanguageId = 1,
                            LevelId = 5,
                            PricePerHour = 28,
                            TutorId = 5
                        },
                        new
                        {
                            Id = 9,
                            Experience = 8,
                            LanguageId = 5,
                            LevelId = 4,
                            PricePerHour = 38,
                            TutorId = 6
                        },
                        new
                        {
                            Id = 10,
                            Experience = 10,
                            LanguageId = 2,
                            LevelId = 5,
                            PricePerHour = 25,
                            TutorId = 6
                        });
                });

            modelBuilder.Entity("Services.Database.TutorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SessionTag", b =>
                {
                    b.Property<int>("SessionsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("SessionsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SessionTag");
                });

            modelBuilder.Entity("Services.Database.Admin", b =>
                {
                    b.HasBaseType("Services.Database.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "admin@justspeak.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        });
                });

            modelBuilder.Entity("Services.Database.Student", b =>
                {
                    b.HasBaseType("Services.Database.User");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "james.brown@justspeak.com",
                            FirstName = "James",
                            LastName = "Brown",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "maria.garcia@justspeak.com",
                            FirstName = "Maria",
                            LastName = "Garcia",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "robert.taylor@justspeak.com",
                            FirstName = "Robert",
                            LastName = "Taylor",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "jennifer.davis@justspeak.com",
                            FirstName = "Jennifer",
                            LastName = "Davis",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "william.wilson@justspeak.com",
                            FirstName = "William",
                            LastName = "Wilson",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        });
                });

            modelBuilder.Entity("Services.Database.Tutor", b =>
                {
                    b.HasBaseType("Services.Database.User");

                    b.HasDiscriminator().HasValue("Tutor");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "sarah.johnson@justspeak.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "michael.chen@justspeak.com",
                            FirstName = "Michael",
                            LastName = "Chen",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "emma.williams@justspeak.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "david.martinez@justspeak.com",
                            FirstName = "David",
                            LastName = "Martinez",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 3, 22, 31, 38, 116, DateTimeKind.Utc).AddTicks(3555),
                            Email = "lisa.anderson@justspeak.com",
                            FirstName = "Lisa",
                            LastName = "Anderson",
                            PasswordHash = "FwwLVIQL84DVKossXEHd0t7yQCaQDGlkEKcND+nsCEQ=",
                            PasswordSalt = "vew6OzACMpTcQjQiOQEgEQ=="
                        });
                });

            modelBuilder.Entity("Services.Database.AvailableDay", b =>
                {
                    b.HasOne("Services.Database.TutorSchedule", "TutorSchedule")
                        .WithMany("AvailableDays")
                        .HasForeignKey("TutorScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TutorSchedule");
                });

            modelBuilder.Entity("Services.Database.Certificate", b =>
                {
                    b.HasOne("Services.Database.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Tutor", "Tutor")
                        .WithMany("Certificates")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Services.Database.Comment", b =>
                {
                    b.HasOne("Services.Database.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Services.Database.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Services.Database.Like", b =>
                {
                    b.HasOne("Services.Database.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId");

                    b.HasOne("Services.Database.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.HasOne("Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Services.Database.Payment", b =>
                {
                    b.HasOne("Services.Database.StudentTutorSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Services.Database.Post", b =>
                {
                    b.HasOne("Services.Database.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Services.Database.Session", b =>
                {
                    b.HasOne("Services.Database.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Services.Database.StudentLanguage", b =>
                {
                    b.HasOne("Services.Database.Language", "Language")
                        .WithMany("StudentLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Student", "Student")
                        .WithMany("StudentLanguages")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Services.Database.StudentTutorSession", b =>
                {
                    b.HasOne("Services.Database.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Services.Database.TutorLanguage", b =>
                {
                    b.HasOne("Services.Database.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Tutor", "Tutor")
                        .WithMany("TutorLanguages")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Level");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Services.Database.TutorSchedule", b =>
                {
                    b.HasOne("Services.Database.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SessionTag", b =>
                {
                    b.HasOne("Services.Database.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Services.Database.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Services.Database.Comment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Services.Database.Language", b =>
                {
                    b.Navigation("StudentLanguages");
                });

            modelBuilder.Entity("Services.Database.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Services.Database.TutorSchedule", b =>
                {
                    b.Navigation("AvailableDays");
                });

            modelBuilder.Entity("Services.Database.Student", b =>
                {
                    b.Navigation("StudentLanguages");
                });

            modelBuilder.Entity("Services.Database.Tutor", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("TutorLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
